#include <deployment.h>
#include <po_hi_gqueue.h>
#include <po_hi_types.h>
#include <request.h>
#include <types.h>
#include <subprograms.h>
#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_port_t __po_hi_controller_controllerinput_local_destinations[1] = {plant_global_controllerinput};
__po_hi_uint8_t __po_hi_controller_woffsets[__po_hi_controller_nb_ports];
__po_hi_uint8_t __po_hi_controller_offsets[__po_hi_controller_nb_ports];
__po_hi_uint8_t __po_hi_controller_used_size[__po_hi_controller_nb_ports];
__po_hi_uint8_t __po_hi_controller_empties[__po_hi_controller_nb_ports];
__po_hi_uint8_t __po_hi_controller_first[__po_hi_controller_nb_ports];
__po_hi_request_t __po_hi_controller_recent[__po_hi_controller_nb_ports];
__po_hi_port_t __po_hi_controller_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_controller_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_controller_history[0];
__po_hi_uint8_t __po_hi_controller_n_dest[__po_hi_controller_nb_ports] = {1,0};
__po_hi_int8_t __po_hi_controller_fifo_size[__po_hi_controller_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_INDATA};
__po_hi_port_t* __po_hi_controller_destinations[__po_hi_controller_nb_ports] = {__po_hi_controller_controllerinput_local_destinations,NULL};

/*!
 * \fn void controller_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task controller
 *
 * When the generated application received a request,it calls a main delivery 
 * function that redirectsto local functions for each task. This function 
 * (controller_deliver) stores the incoming request for the taskcontroller
 */
void controller_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case controller_global_outputfeedback:
    {
      __po_hi_gqueue_store_in (sunseekercontroller_controller_k, controller_local_outputfeedback, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* controller_job (void)
 * \brief Function executed by the task controller
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : Controller*/
/*  Get the IN ports values*/
void* controller_job (void)
{
  __po_hi_request_t outputfeedback_request;
  beacon_standard__single_float controllerinput_request_var;
  __po_hi_request_t controllerinput_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (sunseekercontroller_controller_k, __po_hi_controller_nb_ports, __po_hi_controller_queue, __po_hi_controller_fifo_size, __po_hi_controller_first, __po_hi_controller_offsets, __po_hi_controller_woffsets, __po_hi_controller_n_dest, __po_hi_controller_destinations, __po_hi_controller_used_size, __po_hi_controller_history, __po_hi_controller_recent, __po_hi_controller_empties, __po_hi_controller_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (sunseekercontroller_controller_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (sunseekercontroller_controller_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (sunseekercontroller_controller_k, controller_local_outputfeedback))
    {
          __po_hi_gqueue_get_value (sunseekercontroller_controller_k, controller_local_outputfeedback, &(outputfeedback_request));
      __po_hi_gqueue_next_value (sunseekercontroller_controller_k, controller_local_outputfeedback);

    }
    /*  Call implementation*/
    sunseeker__sunseekercontroller_subprogram_impl (&(controllerinput_request_var), outputfeedback_request.vars.controller_global_outputfeedback.controller_global_outputfeedback);
    /*  Set the OUT port values*/
    controllerinput_request.vars.controller_global_controllerinput.controller_global_controllerinput = controllerinput_request_var;
    controllerinput_request.port = controller_global_controllerinput;
    __po_hi_gqueue_store_out (sunseekercontroller_controller_k, controller_local_controllerinput, &(controllerinput_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (sunseekercontroller_controller_k, controller_global_controllerinput);
    __po_hi_wait_for_next_period (sunseekercontroller_controller_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery. To specify which function should be 
 * called, it extracts  the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case sunseekercontroller_controller_k_entity:
    {
      controller_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


