#include <deployment.h>
#include <po_hi_types.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_bus_id device_device_a_accessed_buses[1] = {bus_the_bus};
extern __po_hi_c_ip_conf_t* pohidrv_device_a;
__po_hi_bus_id device_device_b_accessed_buses[1] = {bus_the_bus};
extern __po_hi_c_ip_conf_t* pohidrv_device_b;
__po_hi_entity_t __po_hi_port_global_to_entity[__PO_HI_NB_PORTS] = {sunseekerplant_plant_k_entity,sunseekerplant_plant_k_entity,sunseekercontroller_controller_k_entity,sunseekercontroller_controller_k_entity};
char* __po_hi_port_global_names[__PO_HI_NB_PORTS] = {"plant_global_controllerinput","plant_global_outputfeedback","controller_global_controllerinput","controller_global_outputfeedback"};
char* __po_hi_port_global_model_names[__PO_HI_NB_PORTS] = {"controllerinput","outputfeedback","controllerinput","outputfeedback"};
__po_hi_port_kind_t __po_hi_port_global_kind[__PO_HI_NB_PORTS] = {__PO_HI_IN_DATA_INTER_PROCESS,__PO_HI_OUT_DATA_INTER_PROCESS,__PO_HI_OUT_DATA_INTER_PROCESS,__PO_HI_IN_DATA_INTER_PROCESS};
__po_hi_uint32_t __po_hi_port_global_data_size[__PO_HI_NB_PORTS] = {4,4,4,4};
__po_hi_uint32_t __po_hi_port_global_queue_size[__PO_HI_NB_PORTS] = {1,1,1,1};
__po_hi_local_port_t __po_hi_port_global_to_local[__PO_HI_NB_PORTS] = {plant_local_controllerinput,plant_local_outputfeedback,controller_local_controllerinput,controller_local_outputfeedback};
__po_hi_node_t __po_hi_entity_table[__PO_HI_NB_ENTITIES] = {sunseekerplant_k,sunseekercontroller_k};
__po_hi_uint8_t __po_hi_deployment_endiannesses[__PO_HI_NB_NODES] = {__PO_HI_LITTLEENDIAN,__PO_HI_LITTLEENDIAN};
char* __po_hi_devices_naming[__PO_HI_NB_DEVICES] = {"noaddr","noaddr"};
__po_hi_uint32_t* __po_hi_devices_configuration_values[__PO_HI_NB_DEVICES] = {(__po_hi_uint32_t*)&(pohidrv_device_a),(__po_hi_uint32_t*)&(pohidrv_device_b)};
__po_hi_uint32_t __po_hi_devices_nb_accessed_buses[__PO_HI_NB_DEVICES] = {1,1};
__po_hi_bus_id* __po_hi_devices_accessed_buses[__PO_HI_NB_DEVICES] = {device_device_a_accessed_buses,device_device_b_accessed_buses};
__po_hi_device_id __po_hi_port_to_device[__PO_HI_NB_PORTS] = {device_a_device_id,device_a_device_id,device_b_device_id,device_b_device_id};
__po_hi_port_t __po_hi_devices_to_nodes[__PO_HI_NB_DEVICES] = {sunseekerplant_k,sunseekercontroller_k};

