#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <drivers/configuration/ip.h>
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE sunseekercontroller_k

#define __po_hi_controller_nb_ports 2

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  sunseekerplant_k = 0,
  sunseekercontroller_k = 1
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  sunseekerplant_plant_k_entity = 0,
  sunseekercontroller_controller_k_entity = 1,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  sunseekercontroller_controller_k = 0,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1,
  device_a_device_id = 0,
  device_b_device_id = 1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1,
  bus_the_bus = 0
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 1

#define __PO_HI_TASKS_STACK 0

#define __PO_HI_NB_PROTECTED 0

#define __PO_HI_NB_NODES 2

#define __PO_HI_NB_ENTITIES 2

#define __PO_HI_NB_PORTS 4

typedef enum
{
  plant_global_controllerinput = 0,
  plant_global_outputfeedback = 1,
  controller_global_controllerinput = 2,
  controller_global_outputfeedback = 3,
  invalid_port_t = -1,
  constant_out_identifier = 5
} __po_hi_port_t;

typedef enum
{
  plant_local_controllerinput = 0,
  plant_local_outputfeedback = 1,
  controller_local_controllerinput = 0,
  controller_local_outputfeedback = 1,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 2

#define __PO_HI_NB_BUSES 1

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_NEED_DRIVER_SOCKETS 1

#endif
