###################################################
# This Makefile has been generated automatically  #
# by the Ocarina AADL toolsuite.                  #
# Do not edit this file, all your changes will    #
# be overridden at the next code generation.      #
###################################################

#  Distributed application name : sunseekercontrolsystem_type_dist
#  Node name                    : sunseekercontroller
#  Execution platform           : PLATFORM_NATIVE
#  Transport API                : TRANSPORT_USER

USER_OBJS =  sunseekercontroller.o \
	   devicesconf.o

MAINAPP = sunseekercontrolsystem_type_dist
BINARY = sunseekercontroller
TARGET = native
NEED_TRANSPORT = yes
RUNTIME_PATH=/home/assert/tool-inst/include/ocarina/runtime/polyorb-hi-c
USER_SOURCES_DIRS= /home/assert/tool-src/po-hi-c/examples/aadlv2/sunseeker/
ASN_SOURCES=
include $(RUNTIME_PATH)/make/Makefile.common

compile-c-files:
	$(CC) -c $(INCLUDE) $(CFLAGS) -I'/home/assert/tool-src/po-hi-c/examples/aadlv2/sunseeker/' '/home/assert/tool-src/po-hi-c/examples/aadlv2/sunseeker/sunseekercontroller.c' -o sunseekercontroller.o
	$(CC) -c $(INCLUDE) $(CFLAGS) -I'/home/assert/tool-src/po-hi-c/examples/aadlv2/sunseeker/' '/home/assert/tool-src/po-hi-c/examples/aadlv2/sunseeker/devicesconf.c' -o devicesconf.o

compile-ada-files:

