#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_single_float 
    (beacon_standard__single_float value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_float32 (value, message, offset);
}

void __po_hi_unmarshall_type_single_float 
    (beacon_standard__single_float* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_float32 (value, message, offset);
}

void __po_hi_marshall_request_plant_controllerinput 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_single_float (request->vars.plant_global_controllerinput.plant_global_controllerinput, message, offset);
}

void __po_hi_unmarshall_request_plant_controllerinput 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_single_float (&(request->vars.plant_global_controllerinput.plant_global_controllerinput), message, offset);
}

void __po_hi_marshall_request_plant_outputfeedback 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_single_float (request->vars.plant_global_outputfeedback.plant_global_outputfeedback, message, offset);
}

void __po_hi_unmarshall_request_plant_outputfeedback 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_single_float (&(request->vars.plant_global_outputfeedback.plant_global_outputfeedback), message, offset);
}

void __po_hi_marshall_request_controller_controllerinput 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_single_float (request->vars.controller_global_controllerinput.controller_global_controllerinput, message, offset);
}

void __po_hi_unmarshall_request_controller_controllerinput 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_single_float (&(request->vars.controller_global_controllerinput.controller_global_controllerinput), message, offset);
}

void __po_hi_marshall_request_controller_outputfeedback 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_single_float (request->vars.controller_global_outputfeedback.controller_global_outputfeedback, message, offset);
}

void __po_hi_unmarshall_request_controller_outputfeedback 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_single_float (&(request->vars.controller_global_outputfeedback.controller_global_outputfeedback), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case plant_global_controllerinput:
    {
      __po_hi_marshall_request_plant_controllerinput (request, message, &(offset));

      break;
    }
    case plant_global_outputfeedback:
    {
      __po_hi_marshall_request_plant_outputfeedback (request, message, &(offset));

      break;
    }
    case controller_global_controllerinput:
    {
      __po_hi_marshall_request_controller_controllerinput (request, message, &(offset));

      break;
    }
    case controller_global_outputfeedback:
    {
      __po_hi_marshall_request_controller_outputfeedback (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case plant_global_controllerinput:
    {
      __po_hi_unmarshall_request_plant_controllerinput (request, message, &(offset));

      break;
    }
    case plant_global_outputfeedback:
    {
      __po_hi_unmarshall_request_plant_outputfeedback (request, message, &(offset));

      break;
    }
    case controller_global_controllerinput:
    {
      __po_hi_unmarshall_request_controller_controllerinput (request, message, &(offset));

      break;
    }
    case controller_global_outputfeedback:
    {
      __po_hi_unmarshall_request_controller_outputfeedback (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


