#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"controller_global_controllerinput","controller_global_outputfeedback","plant_global_controllerinput","plant_global_outputfeedback"};

