#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      beacon_standard__single_float controller_global_controllerinput;

    } controller_global_controllerinput;

    struct
    {
      beacon_standard__single_float controller_global_outputfeedback;

    } controller_global_outputfeedback;

    struct
    {
      beacon_standard__single_float plant_global_controllerinput;

    } plant_global_controllerinput;

    struct
    {
      beacon_standard__single_float plant_global_outputfeedback;

    } plant_global_outputfeedback;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
