#include <types.h>
#include <deployment.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_sunseekercontroller 
    (beacon_standard__single_float* controllerinput,
    beacon_standard__single_float outputfeedback);
void sunseeker__sunseekercontroller_subprogram_impl 
    (beacon_standard__single_float* controllerinput,
    beacon_standard__single_float outputfeedback)
{

  user_sunseekercontroller (controllerinput, outputfeedback);
}

void __po_hi_driver_sockets_send 
    (__po_hi_device_id dev_id);
void ocarina_drivers_ip_pohic__spg_eth_linux_sender_i 
    (__po_hi_device_id dev_id)
{

  __po_hi_driver_sockets_send (dev_id);
}


